### ISSUE TITLE
new line

### ISSUE THREAD

**Issue by swana1337** [DanieLeeuwner/JSZPL#10]
is there a possible soluton to tell the text.text, that there are new lines ? so to split the text in 3 lines like 

text.text = "abc" + \n + "...." and so on ? 

i tried it with 
\n
\0A
_0A
but nothing worked.

kind regards

**Comment by DanieLeeuwner** [comment]
I added line break functionality to the latest version. You can inspect test.js and run the `npm test` command to view the results of this enhancement.

Note the addition of a 'lineSpacing' property to the Text component. This adds additional vertical space between the resulting lines. The lines of text are aligned as a block and not individually aligned, this alignment can be fixed as an additional enhancement.

![image](https://user-images.githubusercontent.com/16599761/120069257-365a4100-c085-11eb-814f-e60afb1222c4.png)

**Comment by swana1337** [comment]
thank you very much !!!
