### ISSUE TITLE
SizeType is not defined

### ISSUE THREAD

**Issue by dazes97** [DanieLeeuwner/JSZPL#13]
I was trying tu use a grid component, but it throws an error "SizeType is not defined" I solved it by adding:
`const SizeType = require('../enums/size-type');
`
at the beginning of the file
the version I am using is:
`    "jszpl": "^1.1.0",
`
 at the grid component file in my nodejs modules
the problem was at line 70
I am not a github expert so this is my first issue report.
hope my problem and solution were clear.

**Comment by DanieLeeuwner** [comment]
Thank you for reporting the issue. It has been resolved and published to version 1.1.2
