### ISSUE TITLE
Ability to change size of a font

### ISSUE THREAD

**Issue by rodgtello** [DanieLeeuwner/JSZPL#15]
Exploring the forks of this project, i found an old one adding that functionality to the project, is very outdated so I'm not sure how should this fir into this project, have you considered adding an option to change the size of the Text elements?

https://github.com/n1mda/JSZPL/commit/266a894a77bc9dbbe4cb667723cc9733b8a6d35d
^^^this is the old fork that added size to the text elements

**Comment by DanieLeeuwner** [comment]
Functionality added by cadb3c130583ab6a165f4bf1622cfe491afda5d0. Feel free to take a look at the commit and reopen if any issues arise.
