### ISSUE TITLE
Text alignment does not align correctly on vertical axis

### ISSUE THREAD

**Issue by nnaku** [DanieLeeuwner/JSZPL#17]
Found align issue while developing label layout! 

Current result of alignment  (100x50 label same as test helper) 
![image](https://user-images.githubusercontent.com/19587635/137858396-31dde137-f52d-44e4-b21a-1146070ea0ee.png)

Expected result of alignment  (100x50 label same as test helper) 
![image](https://user-images.githubusercontent.com/19587635/137858696-cd957622-ef07-4d84-96b4-bc839fc8c900.png)

**Comment by DanieLeeuwner** [comment]
PR merged into development, thank you.
