### ISSUE TITLE
expanding this project?

### ISSUE THREAD

**Issue by NextStepGuru** [DanieLeeuwner/JSZPL#2]
Are you interested in expanding this project? Would you be open to help?

**Comment by DanieLeeuwner** [comment]
All functionality I needed was added. When time presents itself I plan to fix the items outlined in the 'known issues' area, and implement the 'roadmap' items. I am open to help/suggestions on features.

**Comment by DanieLeeuwner** [comment]
@NextStepGuru , I created this project to support a visual designer (included into demo folder in b1df8a5c5bb8ba256ee7c0853161ee3499488e21). I am planning to re-write the demo application into something more usable using Angular.
