### ISSUE TITLE
Multiline setting on text component 

### ISSUE THREAD

**Issue by dotamir** [DanieLeeuwner/JSZPL#20]
Hi. Thanks for this great library. It helps me a lot recently and I got interest in doing some contributions if it’s possible.

I wonder why multiline setting didn’t implemented on text component? It doesn’t seem to make an issue on the component. Is there any specific reason?

I’d like to contribute and implement this if that’s okay.

**Comment by DanieLeeuwner** [comment]
Hi, I am really happy that this library is helping you.

Are you referring to something similar than what was implemented for issue #10?

**Comment by dotamir** [comment]
Hi.

No, I'm referring to the issue that you've mentioned in Known Issues that didn't implement. The Multi-line text alignment that you set a number to say text can be broken into lines automatically.

As you see in the screenshot below lines are getting together:
![Screen Shot 2022-01-25 at 11 16 41](https://user-images.githubusercontent.com/16477296/150933848-0d5ecd45-4432-44c7-922c-de269e438636.png)

Code:
```
^FB332,1,0,C,0
^FDVillage game - PS4 - Lorem ipsum - Lorem ipsum - Lorem ipsum^FS
```

And if we set FB settings to this:
```
^FB332,2,0,C,0
```

Text will be broken into two lines.

**Comment by DanieLeeuwner** [comment]
The multi-line text alignment known issue refers to the problem illustrated here:

![zpl_label_1643101157294](https://user-images.githubusercontent.com/16599761/150949119-e1d421ed-072d-466a-be57-15ff743c72e2.png)

What you seem to be referring to is specifying the number of lines text should be displayed in if it overflows its given container. From the ZPLII spec it does not seem like any issue may arise if we always set the 'maximum number of lines in text block' (parameter b) to a large number such as 1000.

The implementation here would need to be added in two places:
- Text.generateZPL: here it is as simple as adding the max line count
- Text.generateBinaryImage: here we would need to look at the available space and break the lines in a similar fashion as implemented in ZPL firmware

The generateBinaryImage function is used by the designer implementation. You can take a look at the designer by running the JSZPL/demo/index.html file.

**Comment by dotamir** [comment]
So you are suggesting instead of adding an option to the text component to set a maximum number of lines just set 1000 as a constant value?

**Comment by DanieLeeuwner** [comment]
Yes, that is what I am suggesting.

It seems like ZPL firmware forces character wrapping, which means that the update to Text.generateBinaryImage would not be much work.

**Comment by dotamir** [comment]
Hey. Sorry I couldn't follow this in recent days. I'd need some advice regarding Text.generateBinaryImage. What should I change in there?

**Comment by DanieLeeuwner** [comment]
I am in the process of deprecating the `generateBinaryImage` methods in favor of an external package to render ZPL. Please create a pull request with the changes you made for supporting text wrapping.

**Comment by dotamir** [comment]
@DanieLeeuwner Hi. I made a PR for my changes. #24
