### ISSUE TITLE
Spacing.js horizontal difference calculation incorrect

### ISSUE THREAD

**Issue by yingfengchen** [DanieLeeuwner/JSZPL#21]
it should be Math.abs(this.left - this.right) ???

**Comment by DanieLeeuwner** [comment]
Suggested changes: `Spacing.js (20)`
```diff
get horizontalDifference() {
-    return Math.abs(this.left - this.top);
+    return Math.abs(this.left - this.right);
}
```

**Comment by DanieLeeuwner** [comment]
Thank you for the feedback. The issue has been fixed and will be added to the next release (version 1.1.5).
