### ISSUE TITLE
Where is the Dist folder?

### ISSUE THREAD

**Issue by mukdagr8** [DanieLeeuwner/JSZPL#28]
I have installed the package using npm but there is no dist folder included. 

I tried including the config file in my own webpack.mix but I get an error

UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/var/www/html/public/jszpl.bundle.js'

const path = require('path');

mix.webpackConfig({
    mode: 'production',
    entry: '/node_modules/jszpl/src/jszpl.js',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'jszpl.bundle.js',
        libraryTarget: 'umd'
    },
});

**Comment by DanieLeeuwner** [comment]
The `.npmignore` file was updated to include the `dist` directory. Please update to the latest version of the package (`1.1.8`) and try again.
