### ISSUE TITLE
FontFamilyDefinition undefined

### ISSUE THREAD

**Issue by looksystems** [DanieLeeuwner/JSZPL#3]
Great library, thank you.

When I import the library (using yarn and webpack) the FontFamilyDefinition variable is not defined.

For example:

```
import jszpl from 'jszpl'
new jszpl.FontFamily(jszpl.FontFamilyName.D);
```

will throw an error.

Oddly, commenting out the following line at the top of jszpl.js:

// var require = require || function() {};

resolves the issue.

Am I missing something obvious?

**Comment by DanieLeeuwner** [comment]
Some lines in [jszpl.js](/DanieLeeuwner/JSZPL/blob/master/jszpl.js)
```js
var require = require || function() {};
var FontFamilyDefinition = FontFamilyDefinition || require('./zpl-fonts');
```

and [zpl-fonts.js](/DanieLeeuwner/JSZPL/blob/master/zpl-fonts.js)
```js
var module = module || {};
var FontFamilyDefinition = module.exports = {
  ...
```

are hacks to allow for the same JS files to be used without modification for both web, and node. I will look into the correct way of achieving this and get back to you.

In the meantime, you can make the following changes before running webpack.
[jszpl.js](/DanieLeeuwner/JSZPL/blob/master/jszpl.js)
```diff
- var require = require || function() {};
- var FontFamilyDefinition = FontFamilyDefinition || require('./zpl-fonts');
+ var FontFamilyDefinition = require('./zpl-fonts');
```

[zpl-fonts.js](/DanieLeeuwner/JSZPL/blob/master/zpl-fonts.js)
```diff
- var module = module || {};
- var FontFamilyDefinition = module.exports = {
+ module.exports = {
  ...
```

**Comment by DanieLeeuwner** [comment]
@looksystems , can you try the latest commit?

**Comment by looksystems** [comment]
works for me, thank you
