### ISSUE TITLE
qr code encoding

### ISSUE THREAD

**Issue by looksystems** [DanieLeeuwner/JSZPL#4]
As is, the library fails to output aqr code with non-alphanumeric characters.

Here's my fix (for QR codes only):

    var options = '';
    switch (this.type.value) {
      case BarcodeTypeName.QRCode:      
        var magnification = Math.floor(position.height / 10) - 2;
        zpl += '^BQN,2,' + magnification + ',M,7';
        options = 'MM,B' + this.data.length.toString().padStart(4, '0');
        break;
    }
    zpl += '^FD' + options + this.data;
    zpl += '^FS\n';

Hope this saves someone some time wondering why QR codes aren't scanning properly.

**Comment by looksystems** [comment]
Any chance of incorporating this fix?

**Comment by DanieLeeuwner** [comment]
@looksystems Can you please provide an example of the data you are trying to encode?

**Comment by looksystems** [comment]
It's 's been a while - so I don't recall the exact details - but I think the problems were with characters such as ;:<^\`+ etc.

The fix above outputs a fixed length QR code rather than rely on ZPL automatically detecting the format - and getting it wrong. There more info in the ZPL guide: https://www.zebra.com/content/dam/zebra/manuals/printers/common/programming/zpl-zbi2-pm-en.pdf
